# -*- coding: utf-8 -*-
"""webscrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y9CxUQvwbQVBggfYc7EcnOyXhND41L4h
"""

#Author: Evan Collins
#Web Scraping
#3/6/2021
#A simple web scrapping script. 
#The script pulls the body text of the wikipedia article on Spruce Hole Bog in New Hampshire

# Import necessary packages
import bs4
import requests
import lxml

req=requests.get("https://en.wikipedia.org/wiki/Spruce_Hole_Bog") #Get the Spruce Hole Bog wiki page
bog_soup=bs4.BeautifulSoup(req.text,'lxml') # Parse the page text 
bog_p=bog_soup.select('p') # Select 'p' tagged items. These are the text paragraphs of the page. 
for p in bog_p:            # Print every paragraph of the page; every p tagged item. In this case it is only 3 paragraphs, as it is a stub article. 
  print(p.getText())